import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Html5Qrcode} from 'html5-qrcode';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'';
async function api(path,opts={}){const token=localStorage.getItem('messmate_token');const headers={'Content-Type':'application/json',...(opts.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(API+path,{...opts,headers});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={error:t}}if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
const today=()=>new Date().toISOString().slice(0,10);
const mealNames=['breakfast','lunch','dinner'];
const mealLabel=p=>p==='all'?'All meals':p.split(',').map(m=>m[0].toUpperCase()+m.slice(1)).join(' + ');
function Field({label,children}){return <label>{label}{children}</label>}
function Modal({title,close,children}){return <div className="modal-backdrop" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><div className="panel-head"><h3>{title}</h3><button className="close" onClick={close}>×</button></div>{children}</div></div>}
function Auth({onLogin}){const[mode,setMode]=useState('login'),[f,setF]=useState({name:'',email:'',phone:'',password:''}),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setErr('');try{const d=await api(`/api/v1/auth/${mode}`,{method:'POST',body:JSON.stringify(f)});localStorage.setItem('messmate_token',d.token);onLogin()}catch(e){setErr(e.message)}};return <main className="auth-shell"><section className="auth-card"><div className="brand"><span className="logo">M</span><div><b>MessMate</b><small>Mess management, simplified.</small></div></div><h1>{mode==='login'?'Welcome back':'Create owner account'}</h1><p className="muted">Run consumers, meals, subscriptions and collections from one console.</p><form onSubmit={submit}>{mode==='register'&&<><Field label="Name"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Phone"><input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></Field></>}<Field label="Email"><input required type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></Field><Field label="Password"><input required minLength="8" type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></Field>{err&&<div className="error">{err}</div>}<button className="primary full">{mode==='login'?'Sign in':'Create account'}</button></form><button className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setErr('')}}>{mode==='login'?'New to MessMate? Create an account':'Already have an account? Sign in'}</button></section></main>}
function App(){const[logged,setLogged]=useState(!!localStorage.getItem('messmate_token'));return logged?<Console logout={()=>{localStorage.removeItem('messmate_token');setLogged(false)}}/>:<Auth onLogin={()=>setLogged(true)}/>}
function Console({logout}){const[tab,setTab]=useState('dashboard'),[stats,setStats]=useState(null),[consumers,setConsumers]=useState([]),[pending,setPending]=useState([]),[attendance,setAttendance]=useState([]),[expiring,setExpiring]=useState([]),[notice,setNotice]=useState(''),[modal,setModal]=useState(null),[edit,setEdit]=useState(null),[query,setQuery]=useState('');
 const load=async()=>{try{const[s,c,p,a,x]=await Promise.all([api('/api/v1/dashboard'),api('/api/v1/consumers'),api('/api/v1/payments/pending'),api('/api/v1/attendance/today'),api('/api/v1/subscriptions/expiring-today')]);setStats(s);setConsumers(c);setPending(p);setAttendance(a);setExpiring(x)}catch(e){setNotice(e.message)}};useEffect(()=>{load()},[]);const active=useMemo(()=>consumers.filter(c=>c.active),[consumers]);const filtered=useMemo(()=>consumers.filter(c=>`${c.name} ${c.consumer_id} ${c.phone}`.toLowerCase().includes(query.toLowerCase())),[consumers,query]);
 const saveConsumer=async f=>{try{if(edit){await api(`/api/v1/consumers/${edit.id}`,{method:'PATCH',body:JSON.stringify(f)})}else await api('/api/v1/consumers',{method:'POST',body:JSON.stringify(f)});setModal(null);setEdit(null);setNotice(edit?'Consumer updated':'Consumer added');load()}catch(e){setNotice(e.message)}};
 const remove=async c=>{if(!confirm(`Delete ${c.name}?`))return;try{await api(`/api/v1/consumers/${c.id}`,{method:'DELETE'});setNotice('Consumer deleted');load()}catch(e){setNotice(e.message)}};
 return <div className="app"><aside><div className="brand side"><span className="logo">M</span><div><b>MessMate</b><small>Owner console</small></div></div><nav>{[['dashboard','Overview'],['consumers','Consumers'],['subscriptions','Subscriptions'],['attendance','Attendance'],['payments','Payments'],['reports','Reports']].map(([id,l])=><button className={tab===id?'nav active':'nav'} onClick={()=>setTab(id)} key={id}>{l}</button>)}</nav><button className="logout" onClick={logout}>Sign out</button></aside><section className="content"><header><div><p className="eyebrow">MESS MANAGEMENT</p><h2>{tab==='dashboard'?'Good morning 👋':tab[0].toUpperCase()+tab.slice(1)}</h2></div>{tab!=='reports'&&<button className="primary" onClick={()=>setModal('consumer')}>+ Add consumer</button>}</header>{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}</div>}
 {tab==='dashboard'&&<Dashboard stats={stats} consumers={consumers} attendance={attendance} expiring={expiring} openTab={setTab} qr={c=>setModal({type:'qr',consumer:c})}/>} 
 {tab==='consumers'&&<section className="panel"><div className="panel-head"><h3>Consumers ({active.length} active)</h3><input className="search" placeholder="Search name, ID or phone" value={query} onChange={e=>setQuery(e.target.value)}/></div>{filtered.map(c=><ConsumerRow key={c.id} c={c} qr={()=>setModal({type:'qr',consumer:c})} edit={()=>{setEdit(c);setModal('consumer')}} remove={()=>remove(c)}/>) }{!filtered.length&&<Empty text="No consumers found."/>}</section>}
 {tab==='subscriptions'&&<section className="panel"><div className="panel-head"><h3>Subscriptions</h3><button className="primary small" onClick={()=>setModal('subscription')}>+ New subscription</button></div>{consumers.map(c=><div className="row" key={c.id}><div className="grow"><b>{c.name}</b><small>{c.consumer_id} · {mealLabel(c.meal_plan)} · {c.subscription?.end_date&&c.subscription.end_date!=='0001-01-01'?`Ends ${c.subscription.end_date}`:'No subscription'}</small></div><span className={c.subscription?.payment_status==='paid'?'badge ok':'badge pending'}>{c.subscription?.payment_status||'pending'}</span><button className="ghost" onClick={()=>{setEdit(c);setModal('subscription')}}>Renew</button></div>)}{!consumers.length&&<Empty text="Add consumers first."/>}</section>}
 {tab==='attendance'&&<Attendance attendance={attendance} onScan={async(token,meal)=>{try{await api('/api/v1/attendance/scan',{method:'POST',body:JSON.stringify({qr_token:token,meal})});setNotice('Attendance marked');load()}catch(e){setNotice(e.message)}}}/>} 
 {tab==='payments'&&<Payments pending={pending} consumers={consumers} open={()=>setModal('payment')}/>} 
 {tab==='reports'&&<Reports stats={stats} consumers={consumers} pending={pending} attendance={attendance}/>} 
 </section>{modal==='consumer'&&<ConsumerModal initial={edit} close={()=>{setModal(null);setEdit(null)}} save={saveConsumer}/>} {modal==='subscription'&&<SubscriptionModal consumer={edit} consumers={consumers} close={()=>{setModal(null);setEdit(null)}} save={async f=>{try{await api('/api/v1/subscriptions',{method:'POST',body:JSON.stringify(f)});setNotice('Subscription saved');setModal(null);setEdit(null);load()}catch(e){setNotice(e.message)}}}/>} {modal==='payment'&&<PaymentModal consumers={consumers} close={()=>setModal(null)} save={async f=>{try{await api('/api/v1/payments',{method:'POST',body:JSON.stringify(f)});setNotice('Payment recorded');setModal(null);load()}catch(e){setNotice(e.message)}}}/>} {modal?.type==='qr'&&<QRModal c={modal.consumer} close={()=>setModal(null)} loadQR={()=>api(`/api/v1/consumers/${modal.consumer.id}/qr`)}/>}</div>}
function ConsumerRow({c,qr,edit,remove}){return <div className="row consumer"><div className="avatar">{c.name?.[0]?.toUpperCase()}</div><div className="grow"><b>{c.name}</b><small>{c.consumer_id} · {c.phone} · {mealLabel(c.meal_plan)}</small></div><span className={c.active?'badge ok':'badge'}>{c.active?'Active':'Inactive'}</span><button className="ghost" onClick={qr}>QR</button><button className="ghost" onClick={edit}>Edit</button><button className="danger" onClick={remove}>Delete</button></div>}
function Dashboard({stats,consumers,attendance,expiring,openTab,qr}){return <><div className="stats">{[['Active consumers',stats?.active_consumers??'—'],['Expiring today',stats?.expiring_today??'—'],['Pending payments',stats?.pending_payments??'—'],['Today collections',stats?.today_collections!=null?`₹${stats.today_collections}`:'—'],['Today attendance',stats?.today_attendance??'—']].map(([l,v])=><div className="stat" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><div className="grid"><section className="panel"><div className="panel-head"><h3>Expiring today</h3><button className="link" onClick={()=>openTab('subscriptions')}>View subscriptions</button></div>{expiring.slice(0,6).map(c=><div className="row" key={c.id}><div className="grow"><b>{c.name}</b><small>{c.phone} · ₹{c.amount} · {c.payment_status}</small></div>{c.reminder_eligible&&<button className="ghost" onClick={()=>{const p=(c.phone||'').replace(/\D/g,'');window.open(`https://wa.me/${p.startsWith('91')?p:'91'+p}?text=Hi%20${encodeURIComponent(c.name)},%20your%20MessMate%20subscription%20is%20due%20for%20renewal.`,'_blank')}}>WhatsApp</button>}</div>)}{!expiring.length&&<Empty text="Nothing expiring today."/>}</section><section className="panel"><div className="panel-head"><h3>Recent consumers</h3><button className="link" onClick={()=>openTab('consumers')}>View all</button></div>{consumers.slice(0,6).map(c=><div className="row" key={c.id}><div className="avatar">{c.name?.[0]?.toUpperCase()}</div><div className="grow"><b>{c.name}</b><small>{c.consumer_id} · {mealLabel(c.meal_plan)}</small></div><button className="ghost" onClick={()=>qr(c)}>QR</button></div>)}{!consumers.length&&<Empty text="Add your first consumer."/>}</section></div></>}
function Attendance({attendance,onScan}){const[meal,setMeal]=useState('lunch'),[token,setToken]=useState(''),[scanner,setScanner]=useState(null);const start=async()=>{const q=new Html5Qrcode('messmate-reader');setScanner(q);try{await q.start({facingMode:'environment'},{fps:10,qrbox:240},text=>{q.stop().catch(()=>{});setScanner(null);onScan(text,meal)},()=>{})}catch{setScanner(null)}};return <div className="grid"><section className="panel scanner-panel"><h3>Meal attendance</h3><div className="meal-tabs">{mealNames.map(m=><button className={meal===m?'selected':''} onClick={()=>setMeal(m)} key={m}>{m}</button>)}</div><div id="messmate-reader"></div>{!scanner?<button className="primary full" onClick={start}>Open camera scanner</button>:<button className="ghost full" onClick={()=>{scanner.stop().catch(()=>{});setScanner(null)}}>Stop camera</button>}<div className="divider">or enter QR token</div><input value={token} onChange={e=>setToken(e.target.value)} placeholder="QR token UUID"/><button className="primary full" disabled={!token} onClick={()=>{onScan(token,meal);setToken('')}}>Mark attendance</button></section><section className="panel"><h3>Today's attendance ({attendance.length})</h3>{attendance.map((a,i)=><div className="row" key={i}><div className="grow"><b>{a.name||a.consumer_id}</b><small>{a.meal} · {a.scanned_at?new Date(a.scanned_at).toLocaleTimeString():''}</small></div><span className="badge ok">Present</span></div>)}{!attendance.length&&<Empty text="Nothing scanned yet."/>}</section></div>}
function Payments({pending,consumers,open}){return <section className="panel"><div className="panel-head"><h3>Pending payments ({pending.length})</h3><button className="primary small" onClick={open}>+ Record payment</button></div>{pending.map((p,i)=><div className="row" key={i}><div className="grow"><b>{p.name}</b><small>{p.consumer_id} · Due {p.end_date} · ₹{p.due??p.amount}</small></div><span className="badge pending">{p.payment_status}</span></div>)}{!pending.length&&<Empty text="No pending payments."/>}</section>}
function Reports({stats,consumers,pending,attendance}){const paid=consumers.filter(c=>c.subscription?.payment_status==='paid').length;const plans=consumers.reduce((m,c)=>{m[c.meal_plan]=(m[c.meal_plan]||0)+1;return m},{});return <div className="grid"><section className="panel"><h3>Operations summary</h3><div className="report-grid"><div><span>Consumers</span><b>{consumers.length}</b></div><div><span>Active</span><b>{stats?.active_consumers??0}</b></div><div><span>Paid plans</span><b>{paid}</b></div><div><span>Pending</span><b>{pending.length}</b></div><div><span>Today's meals</span><b>{attendance.length}</b></div><div><span>Today's collections</span><b>₹{stats?.today_collections??0}</b></div></div></section><section className="panel"><h3>Meal plans</h3>{Object.entries(plans).map(([p,n])=><div className="row" key={p}><div className="grow"><b>{mealLabel(p)}</b></div><span className="badge">{n}</span></div>)}{!Object.keys(plans).length&&<Empty text="No data yet."/>}</section></div>}
function ConsumerModal({initial,close,save}){
 const initialMeals=initial?.meal_plan?(initial.meal_plan==='all'?mealNames:initial.meal_plan.split(',').filter(Boolean)):mealNames;
 const[f,setF]=useState({name:initial?.name||'',phone:initial?.phone||'',consumer_id:initial?.consumer_id||'',meal_plan:initial?.meal_plan||'all',start_date:initial?.subscription?.start_date&&initial.subscription.start_date!=='0001-01-01'?initial.subscription.start_date:today(),end_date:initial?.subscription?.end_date&&initial.subscription.end_date!=='0001-01-01'?initial.subscription.end_date:today(),amount:initial?.subscription?.amount||'',amount_paid:initial?.subscription?.amount_paid??''});
 const[meals,setMeals]=useState(initialMeals);const toggle=m=>setMeals(v=>v.includes(m)?v.filter(x=>x!==m):[...v,m]);const all=meals.length===3;const submit=e=>{e.preventDefault();if(!meals.length){alert('Select at least one meal');return}if(!initial&&(!f.start_date||!f.end_date)){alert('Start date and end date are required');return}if(!initial&&(Number(f.amount_paid||0)>Number(f.amount||0))){alert('Amount paid cannot be greater than total amount');return}save({...f,meal_plan:all?'all':meals.join(',')});};
 return <Modal title={initial?'Edit consumer':'Add consumer'} close={close}><form onSubmit={submit}><Field label="Name"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Phone"><input required value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></Field>{!initial&&<Field label="Consumer ID"><input value={f.consumer_id} onChange={e=>setF({...f,consumer_id:e.target.value})} placeholder="Auto-generated"/></Field>}<Field label="Meals"><div className="meal-checks"><button type="button" className={all?'meal-choice selected':'meal-choice'} onClick={()=>setMeals(all?[]:mealNames)}>All meals</button>{mealNames.map(m=><button type="button" key={m} className={meals.includes(m)?'meal-choice selected':'meal-choice'} onClick={()=>toggle(m)}>{m[0].toUpperCase()+m.slice(1)}</button>)}</div><small className="form-hint">Select any combination. A consumer can have 2 or 3 meals.</small></Field>{!initial&&<><div className="form-section-title">Subscription & payment</div><div className="two-fields"><Field label="Start date"><input required type="date" value={f.start_date} onChange={e=>setF({...f,start_date:e.target.value})}/></Field><Field label="End date"><input required type="date" value={f.end_date} onChange={e=>setF({...f,end_date:e.target.value})}/></Field></div><div className="two-fields"><Field label="Total amount"><input required type="number" min="0" step="0.01" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field><Field label="Amount paid"><input required type="number" min="0" step="0.01" value={f.amount_paid} onChange={e=>setF({...f,amount_paid:e.target.value})}/></Field></div><small className="form-hint">Payment status is calculated automatically: pending, partial, or paid.</small></>}</form><button className="primary full" onClick={submit}>Save consumer</button></Modal>}
function SubscriptionModal({consumer,consumers,close,save}){const initial=consumer?.subscription;const[f,setF]=useState({consumer_id:consumer?.id||consumers[0]?.id||'',start_date:initial?.start_date&&initial.start_date!=='0001-01-01'?initial.start_date:today(),end_date:initial?.end_date&&initial.end_date!=='0001-01-01'?initial.end_date:today(),amount:initial?.amount||0,amount_paid:initial?.amount_paid??0,month_label:initial?.month_label||'',payment_status:initial?.payment_status||'pending'});return <Modal title={consumer?'Renew subscription':'New subscription'} close={close}><form onSubmit={e=>{e.preventDefault();if(Number(f.amount_paid)>Number(f.amount)){alert('Amount paid cannot be greater than total amount');return}save(f)}}><Field label="Consumer"><select value={f.consumer_id} onChange={e=>setF({...f,consumer_id:e.target.value})}>{consumers.map(c=><option key={c.id} value={c.id}>{c.name} ({c.consumer_id})</option>)}</select></Field><Field label="Start date"><input required type="date" value={f.start_date} onChange={e=>setF({...f,start_date:e.target.value})}/></Field><Field label="End date"><input required type="date" value={f.end_date} onChange={e=>setF({...f,end_date:e.target.value})}/></Field><Field label="Total amount"><input required type="number" min="0" step="0.01" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field><Field label="Amount paid"><input required type="number" min="0" step="0.01" value={f.amount_paid} onChange={e=>setF({...f,amount_paid:e.target.value})}/></Field><button className="primary full">Save subscription</button></form></Modal>}
function PaymentModal({consumers,close,save}){const[f,setF]=useState({consumer_id:consumers[0]?.id||'',subscription_id:consumers[0]?.subscription?.id||'',amount:0,method:'cash',reference:''});const selected=consumers.find(c=>c.id===f.consumer_id);useEffect(()=>{setF(v=>({...v,subscription_id:selected?.subscription?.id||''}))},[f.consumer_id]);return <Modal title="Record payment" close={close}><form onSubmit={e=>{e.preventDefault();save(f)}}><Field label="Consumer"><select value={f.consumer_id} onChange={e=>setF({...f,consumer_id:e.target.value})}>{consumers.map(c=><option key={c.id} value={c.id}>{c.name} ({c.consumer_id})</option>)}</select></Field>{selected?.subscription&&<Field label="Subscription"><select value={f.subscription_id} onChange={e=>setF({...f,subscription_id:e.target.value})}><option value={selected.subscription.id}>{selected.subscription.month_label||'Current subscription'}</option></select></Field>}<Field label="Amount"><input required type="number" min="0.01" step="0.01" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field><Field label="Method"><select value={f.method} onChange={e=>setF({...f,method:e.target.value})}><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank transfer</option><option value="card">Card</option></select></Field><Field label="Reference"><input value={f.reference} onChange={e=>setF({...f,reference:e.target.value})} placeholder="Optional UPI/transaction reference"/></Field><button className="primary full">Record payment</button></form></Modal>}
function QRModal({c,close,loadQR}){const[data,setData]=useState(null),[err,setErr]=useState('');useEffect(()=>{loadQR().then(setData).catch(e=>setErr(e.message))},[loadQR]);return <Modal title={`${c.name} · QR code`} close={close}>{err?<div className="error">{err}</div>:data?<div className="qr-card"><img alt="Consumer QR" src={`data:image/png;base64,${data.image_base64}`}/><b>{data.name}</b><small>{data.consumer_id}</small><small>{data.qr_token}</small></div>:<Empty text="Generating QR…"/>}</Modal>}
function Empty({text}){return <div className="empty">{text}</div>}
createRoot(document.getElementById('root')).render(<App/>);
